### ISSUE TITLE
Reinstall after uninstall doesn't restore missing Basic Macro dialogs.

### ISSUE THREAD

**Issue by AngrySockPuppet** [jimholgate/readtextextension#13]
In trying to resolve a runtime issue with ReadText 0.8.40, I compared the LibreOffice Basic Macro Organizer contents of a working installation to the broken one.  I noted that, on the broken installation, "Dialog1" and "Dialog3" were missing.  Uninstalling the extension and reinstalling it did not restore the missing dialogs.  I was able to export them from the working installation and import them on the broken installation to return functionality to ReadText.

I'm not really a coding person.  So, it would be a really big help to ensure that missing dialogs are corrected during installation and reinstallation.  I was considering wiping my hard drive and reinstalling the OS (i.e. Windows 8.1 Update pro x64) in order to get ReadText working again.  Fortunately, I mashed the right buttons and got things working again.

Thank you so much.

ReadText is a big part of my life.  It even helped me to quit Microsoft Office. :)

**Comment by jimholgate** [comment]
Thanks for the feedback. 

I'm not sure what the cause of your problem was. I tried downloading that version of the extension from the LibreOffice extensions site with MacOS, Windows and Ubuntu LInux, and I did not encounter your missing dialogue file problem on any of the platforms. It is possible that something interrupted the download of the extension or the decompression of the files into your local extensions directory, so the installation was incomplete.

LibreOffice settings can become corrupt if your computer gets turned off suddenly or if there is an error on your hard disk. If the settings files are corrupt in LibreOffice, you may not be able to use, install, delete or update extensions. To reset the local settings, you can remove or rename the settings directory.

+ Quit LibreOffice.
+ Open the Command Prompt (terminal) application.
+ It will open in your home directory.
+ Type `cd AppData`.
+ Type `cd Roaming`.
+ Type `rmdir /s LibreOffice` or `move LibreOffice LibreOffice.old`.
+ If prompted to confirm, then type `y`, then `return`.
+ Restart LibreOffice.
+ Wait a few seconds for the application to rebuild the settings directory and set the default settings.
+ Quit LibreOffice.
+ Restart LibreOffice.
+ Reinstall your extensions.
+ Restart LibreOffice.

See: [Windows 7 - corrupt LibreOffice local settings](https://sites.google.com/site/readtextextension/home/announcements/windows7-corruptlibreofficelocalsettings)

I'm glad that you finally got it working!

**Comment by AngrySockPuppet** [comment]
Thank you very much for your diligence with this.
The combined notes will likely prove helpful to others.
