### ISSUE TITLE
Is there a shortcut to active this extension on mac?

### ISSUE THREAD

**Issue by Coaggly** [jimholgate/readtextextension#16]

**Comment by jimholgate** [comment]
There is no _built-in_ keyboard shortcut to activate the extension. Normally, you click an icon of a speech balloon on a toolbar to activate the extension. The toolbar item might be hidden in some views (like in full screen mode or using a tabbed toolbar instead of the standard toolbar). 

LibreOffice 6.3 on-line help offers advice for [customizing keyboard shortcuts](https://help.libreoffice.org/6.3/en-US/text/shared/01/06140200.html?DbPAR=SHARED#bm_id2322763). The target for a keyboard shortcut equivalent to clicking the toolbar button would be:

+ _Category_: **My macros > textToSpeech > TextToSpeech**
+ _Function_: **ReadTextAloud**

Some MacOS system keyboard shortcuts cannot be modified, and you might need to install [additional software](https://jdk.java.net/) to make it work properly.
