### ISSUE TITLE
Crash on LO 7.3.x

### ISSUE THREAD

**Issue by figue** [jimholgate/readtextextension#19]
Hi, first things first. Thank you for your extension.

I tried to install this extension on latest LO version, in WIndows or Linux, and a LO Visual window opens and it throws an error.

![image](https://user-images.githubusercontent.com/3238330/161529227-3d88d393-1933-4415-a1e0-d8a08c7d58f5.png)

Also options are "in grey"

![image](https://user-images.githubusercontent.com/3238330/161529513-bd1165cd-0041-4ce3-8a9f-65fe5854246d.png)

**Comment by b3n63r** [comment]
I can confirm this issue in LibreOffice 7.3.1.3 (x64) on Windows 10 Pro 10.0.19044

**Comment by jimholgate** [comment]
An update for LibreOffice 7.3 that solves the issue is available now at the [OpenOffice Extensions site](https://extensions.openoffice.org/en/project/read-text), and should be available at the LibreOffice Extensions site soon. There are working [download links on the Read Text blog](https://sites.google.com/site/readtextextension/home/download).
