### ISSUE TITLE
Sentences in Dutch language are played as Dutch with an English pronounciation

### ISSUE THREAD

**Issue by sebastiaanveld** [jimholgate/readtextextension#20]
I tried this plugin (0.8.57) on the latest version of LibreOffice (7.3.3.2 x64) to play Dutch ("Nederlands") sentences. The sentences are played with an English voice, so I added /language:"nl-NL" or /language:"(SELECTION_LANGUAGE_CODE)" to the command line options which does not solve that issue. Language and spelling is set to Dutch (NlL nl-NL) in LO.

"(TTS_WSCRIPT_VBS)" /language:"nl-NL" "(TMP)"
"(TTS_WSCRIPT_VBS)" /language:"(SELECTION_LANGUAGE_CODE)" "(TMP)"

Is there a solution for this so sentences are played in Dutch language instead of Dutch with an English pronounciation?

**LO version info**
Version: 7.3.3.2 (x64) / LibreOffice Community
Build ID: d1d0ea68f081ee2800a922cac8f79445e4603348
CPU threads: 16; OS: Windows 10.0 Build 22000; UI render: Skia/Vulkan; VCL: win
Locale: nl-NL (nl_NL); UI: nl-NL
Calc: threaded

![afbeelding](https://user-images.githubusercontent.com/37268999/169159538-05b8619c-73ac-42ca-b60c-c8a0fe3077bb.png)

**Comment by jimholgate** [comment]
# Sentences in Dutch language are played as Dutch with an English pronunciation

> Is there a solution for this so sentences are played in Dutch language instead of Dutch with an English pronunciation?

The voices that appear in the Windows Text-to-Speech Control Panel use the classic Windows Speech Application Program Interface (**SAPI**). The voices that only appear in the new Settings dialog use "[Metro](https://support.microsoft.com/en-us/windows/appendix-a-supported-languages-and-voices-4486e345-7730-53da-fcfe-55cc64300f01#WindowsVersion=Windows_10)" voices that work with the default web browser and some applications that use the touch-screen oriented "Metro" interface that Microsoft introduced with Windows 8. "Metro" voices do not work with classic desktop applications.

For English, Windows 10 and 11 provide both SAPI voices and "Metro" voices. For Dutch, Windows 10 and 11 appear to provide a single "Metro" voice (**Frank**), but no SAPI voices.

## How can I get the LibreOffice application to use a SAPI voice for Dutch?

### Free

For many languages, including Dutch, you can try [espeak](http://espeak.sourceforge.net/) - a free application that includes SAPI voices in many languages. These SAPI voices might not match the level of quality you get via Microsoft or other voice distributors.

Translation and other web applications like Google Docs are available that can read many languages aloud in the browser when you are on-line. Since these on-line voices are updated in real-time, they often have better pronunciation than desktop voices. 

On Windows computers, you can [use a command to preview the document in the Edge Web Browser](https://help.libreoffice.org/latest/en-US/text/shared/01/webhtml.html) and select "Frank" as the Metro voice to use to read in Dutch.

### Paid

Windows SAPI voices for many European languages, including Dutch, are available commercially for around twenty-six Euros for individual use. 

Search for "*sapi voices windows 10 dutch*"

**Comment by sebastiaanveld** [comment]
Ack, thanks Jim!
