### ISSUE TITLE
Read Text not using external program

### ISSUE THREAD

**Issue by anhill1948** [jimholgate/readtextextension#25]
I have installed Read Text into LibreOffice 24.2 using Linux Mint 21.3
It won't use Python as the program for reading the text even though it is selected. It seems go straight onto the internet to some google translation program.
What can I do about it?
Andrew.

**Comment by jimholgate** [comment]
On August 25, 2024, Andrew wrote:

> I have installed Read Text into LibreOffice 24.2 using Linux Mint 21.3
> 
> It won't use Python as the program for reading the text even though it
> is selected. It seems go straight onto the internet to some google
> translation program.
> 
> What can I do about it?

1. Check that the system speech-dispatcher works. Open a terminal and check if
   it plays:
   ```bash
   spd-say "Hello Andrew."
   ```

2. If it doesn't play, then try:
   ```bash
   espeak-ng "Hello Andrew."
   ```
3. If speech doesn't work, then check the [Read Text Linux documentation][1]
   to help select a compatible speech platform to install and guide you how
   to install it.
   
4. Try opening the Flatpak version of LibreOffice with a command.
   ```bash
   flatpak open org.libreoffice.LibreOffice --nologo
   ```
5. If LibreOffice 24 does open, then the system could be blocking 
   speech-dispatcher due to Flatpak permission errors, security settings,
   or using a system version of [`python3-speechd`][2] that is 
   incompatible with the Flatpak.

The fact that Flatpak programs can block access to system resources is not an
extension bug, it is a security feature of the Flatpak format. There is no
issue to resolve in the extension code.

1. If the `spd-say` command worked and the `flatpak` command worked,
there is a good chance that you can use an alternative framework
that provides speech synthesis by installing the [Pied][3] voice model
manager for [Piper][4] and [Ffmpeg][5]. Instructions are in this
[Code Description][6] link. 

2. Pied and Piper rely on specific computer architectures and
operating system resources. Therefore, this workaround might
not work on your computer. In this case, you should revert to
the version of LibreOffice that worked previously or upgrade
your Linux distribution.

Good luck!

  [1]: https://sites.google.com/site/readtextextension/home/linux
  [2]: https://packages.debian.org/bookworm/python3-speechd
  [3]: https://pied.mikeasoft.com/
  [4]: https://github.com/rhasspy/piper
  [5]: https://ffmpeg.org//about.html
  [6]: https://github.com/jimholgate/readtextextension/blob/5cd04d8f4037beb5c807c7d36222f954207411d8/Read_Text/python/piper_read_text.py#L45
